#!/bin/bash

build() {
  echo -e "\nBuilding $1"
  cat > Dockerfile <<EOF
FROM ruby:$1

COPY scripts/setup /scripts/setup
RUN /scripts/setup

RUN mkdir /app
WORKDIR /app
EOF
  docker build $3 -t $2:$1 -f Dockerfile .
  rm Dockerfile
}

while [[ $# -gt 1 ]]; do
  key="$1"
  case $key in
    -v|--versions)
      versions="$2"
      shift
      ;;
    -t|--tag)
      tag="$2"
      shift
      ;;
  esac
  shift
done

if [[ ! -z $versions ]]; then
  versions=($versions)
else
  echo "Usage: build --versions [VERSIONS] [BUILD OPTIONS]"
  echo "Example: build --versions \"2.1.5 2.3.0\" --no-cache"
  exit 1
fi

build_options="$@"
for i in ${versions[@]}; do
  build $i $tag $build_options
done
